version: '3'
services:
  db:
    image: postgres:16-alpine
    container_name: db
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '5432:5432'

  backend:
    depends_on:
      - db
    build:
      context: ./backend
    container_name: backend
    environment:
      DATASOURCE_URL: jdbc:postgresql://db:5432/db
      DATASOURCE_USERNAME: postgres
      DATASOURCE_PASSWORD: postgres
    ports:
      - '8080:8080'

  frontend:
    depends_on:
      - backend
    build:
      context: ./frontend
    container_name: frontend
    ports:
      - '5173:5173'